name: autograss

on:
  schedule:
    - cron: '03 15 * * *'  
  workflow_dispatch:  

jobs:
  autograss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update file with date
        run: |
          if [ ! -f $GITHUB_WORKSPACE/autograss_log.txt ]; then
            touch $GITHUB_WORKSPACE/autograss_log.txt
          fi
          echo "grass Updated on $(date +'%Y-%m-%d')" >> $GITHUB_WORKSPACE/autograss_log.txt
      - name: Commit changes
        run: |
          git config --global user.name 'meo-yeong'
          git config --global user.email 'iliad1613@gmail.com'
          git add $GITHUB_WORKSPACE/autograss_log.txt
          git commit -m "grass Updated on $(date +'%Y-%m-%d')"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          branch : main
