name: autograss

on:
  schedule:
    - cron: '03 15 * * *'  # will be automatically executed everyday 23:50 (UTC)
  workflow_dispatch:  # allow manual execution

jobs:
  auto_jandi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update file with date
        run: |
          if [ ! -f $GITHUB_WORKSPACE/auto_jandi_log.txt ]; then
            touch $GITHUB_WORKSPACE/auto_jandi_log.txt
          fi
          echo "grass automatically Updated on $(date +'%Y-%m-%d')" >> $GITHUB_WORKSPACE/auto_jandi_log.txt
      - name: Commit changes
        run: |
          git config --global user.name 'meo-yeong'
          git config --global user.email 'iliad1613@gmail.com'
          git add $GITHUB_WORKSPACE/auto_jandi_log.txt
          git commit -m "Jandi automatically Updated on $(date +'%Y-%m-%d')"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.autograss }} # must add github token name AUTO_JANDI into github actions secret variable
          branch : main # select branch to push
